### ISSUE TITLE
Deployment Failures

### ISSUE THREAD

**Issue by thebeanogamer** [thebeanogamer/linkshortener#97]
```js
  Error --------------------------------------------------
 
  Error: Error: Unable to setup base domain mappings for beano.dev
      at ServerlessCustomDomain.<anonymous> (/home/vsts/work/1/s/node_modules/serverless-domain-manager/dist/index.js:142:27)
      at Generator.throw (<anonymous>)
      at rejected (/home/vsts/work/1/s/node_modules/serverless-domain-manager/dist/index.js:5:65)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              12.16.3
     Framework Version:         1.70.0
     Plugin Version:            3.6.11
     SDK Version:               2.3.0
     Components Version:        2.30.10

```

Fixes once after deleting the domain and running `serverless create_domain`. Need to confirm if CloudFormation will be rolling-back automatically or just pushing ahead. Should run a debug deploy.

**Comment by thebeanogamer** [comment]
[Debug run](https://dev.azure.com/thebeanogamer/Link%20Shortener/_build/results?buildId=840&view=logs&j=e07742bd-189a-5079-918b-43f8b2f94b89&t=36f9144f-a45f-5b35-66d0-36ec4e578454)

```js
2020-05-08T16:43:49.4095669Z Serverless: [AWS apigatewayv2 200 0.348s 0 retries] getApiMappings({ DomainName: 'beano.dev' })
2020-05-08T16:43:49.4173213Z Serverless: [AWS apigateway undefined 0.007s 0 retries] updateBasePathMapping({
2020-05-08T16:43:49.4176793Z   basePath: '',
2020-05-08T16:43:49.4181681Z   domainName: 'beano.dev',
2020-05-08T16:43:49.4182412Z   patchOperations: [
2020-05-08T16:43:49.4183489Z     { op: 'replace', path: '/basePath', value: '(none)' },
2020-05-08T16:43:49.4184229Z     [length]: 1
2020-05-08T16:43:49.4184712Z   ]
2020-05-08T16:43:49.4185045Z })
2020-05-08T16:43:49.4185868Z Serverless Domain Manager: Error: beano.dev:  UriParameterError: Expected uri parameter to have length >= 1, but found "" for params.basePath
2020-05-08T16:43:49.4187176Z Serverless Domain Manager: Error: beano.dev:  Error: Error: beano.dev: Unable to update basepath mapping.
```

`UriParameterError: Expected uri parameter to have length >= 1, but found "" for params.basePath`
Hmmm

**Comment by thebeanogamer** [comment]
Appears to be a known issue amplify-education/serverless-domain-manager#332
